### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by kmille** [pabra/haushaltsbuch#1]
Hey, I want to test you haushaltsbuch (some screenshots would be nice).

When I use your instructions I get the following erros:

(venv) [1] kmille@homebox> ./run.py init_db                                                                                           /tmp/venv/haushaltsbuch
Traceback (most recent call last):
  File "/tmp/venv/lib/python3.5/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
ImportError: No module named 'config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run.py", line 5, in <module>
    from app import app
  File "/tmp/venv/haushaltsbuch/app/__init__.py", line 11, in <module>
    app.config.from_object('config')
  File "/tmp/venv/lib/python3.5/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/tmp/venv/lib/python3.5/site-packages/werkzeug/utils.py", line 443, in import_string
    sys.exc_info()[2])
  File "/tmp/venv/lib/python3.5/site-packages/werkzeug/_compat.py", line 137, in reraise
    raise value.with_traceback(tb)
  File "/tmp/venv/lib/python3.5/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
werkzeug.utils.ImportStringError: import_string() failed for 'config'. Possible reasons are:

- missing __init__.py in a package;
- package or module path not included in sys.path;
- duplicated package or module name taking precedence in sys.path;
- missing module, class, function or variable;

Debugged import:

- 'config' not found.

Original exception:

ImportError: No module named 'config'

(venv) [1] kmille@homebox> pip install config                                                                                         /tmp/venv/haushaltsbuch
Collecting config
Installing collected packages: config
Successfully installed config-0.3.9
(venv) kmille@homebox> ./run.py init_db                                                                                               /tmp/venv/haushaltsbuch
Traceback (most recent call last):
  File "./run.py", line 5, in <module>
    from app import app
  File "/tmp/venv/haushaltsbuch/app/__init__.py", line 11, in <module>
    app.config.from_object('config')
  File "/tmp/venv/lib/python3.5/site-packages/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/tmp/venv/lib/python3.5/site-packages/werkzeug/utils.py", line 418, in import_string
    __import__(import_name)
  File "/tmp/venv/lib/python3.5/site-packages/config.py", line 733
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Now I'm not really shure if installed the wrong 'config'. Thanks!
I am running an Arch :-)

**Comment by kmille** [comment]
fixed it by renaming config.template.py to config.py...
Please update your documentation. git clone is also missing.
